# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Deploy_back_end
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Deploy_back_end'

  - script: |
      cd back-end
      npm install
      npm start
    

- job: Deploy_front_end
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      cd front-end
      npm install
      npm run build
  displayName: 'Deploy_front_end'

